export const REQUEST_EMPLOYEES = 'REQUEST_EMPLOYEES';
export const RECEIVE_EMPLOYEES = 'RECEIVE_EMPLOYEES';
export const FAIL_REQUEST_EMPLOYEES = 'FAIL_REQUEST_EMPLOYEES';

export const REQUEST_ABOUT = 'REQUEST_ABOUT';
export const RECEIVE_ABOUT = 'RECEIVE_ABOUT';